# Generated by Django 5.0.4 on 2024-04-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_book_book_cover_alter_book_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the author', max_length=50, verbose_name='Author Name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category of the book', max_length=50, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('hard', 'Hard'), ('soft', 'Soft'), ('special', 'Special')], max_length=7, null=True, verbose_name='Cover Type'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, help_text='Enter the name of the author', on_delete=django.db.models.deletion.CASCADE, to='market.author', verbose_name='Author Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='Enter the category of the book', to='market.category', verbose_name='Category'),
        ),
    ]
